Sharver/Models/Post.cs
using Sharver.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Sharver.Models
{

    public class Post
    {
        [Required]
        public int Id { get; set; }

        [DisplayName("Wynik")]
        public int Score { get; set; } = 0;

        [DisplayName("Tytuł")]
        [DataType(DataType.Text)]
        [Required]
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        public string Content { get; set; }


        public string Flair { get; set; }

        //0 - text
        //1 - url
        //2 - file
        public Byte Type { get; set; } = 0;

        [DisplayName("Czas stworzenia")]
        [DataType(DataType.DateTime)]
        public DateTime Created_at { get; set; }

        [DisplayName("Czas ostatniej aktualizacji")]
        [DataType(DataType.DateTime)]
        public DateTime? Updated_at { get; set; }

        //Foreign
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<PostRating> PostRating { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        
    }

    public class PostDTO
    {
        [Required]
        public string Title { get; set; }
        public string Content { get; set; }
        public string Flair { get; set; }
        public Byte Type { get; set; } = 0;
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

Sharver/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharver.Models;
using Microsoft.AspNet.Identity;

namespace Sharver.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public async Task<ActionResult> Index()
        {
            var comments = db.Comments.Include(c => c.Parent).Include(c => c.User);
            return View(await comments.ToListAsync());
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.UserId = User.Identity.GetUserId();
                comment.Created_at = DateTime.Now;
                db.Comments.Add(comment);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Posts", new { id = comment.PostId });
            }
            return RedirectToAction("Details", "Posts", new { id = comment.PostId });
        }
        
        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Exclude = "Created_at")]Comment comment)
        {
            if (ModelState.IsValid)
            {
                var change = db.Comments.FirstOrDefault(p => p.Id == comment.Id);
                change.Content = comment.Content;
                change.Updated_at = DateTime.Now;
                db.Entry(comment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Posts", new { id = comment.PostId });
            }
            return RedirectToAction("Details", "Posts", new { id = comment.PostId });
        }
        
        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Comment comment = await db.Comments.FindAsync(id);
            db.Comments.Remove(comment);
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Posts", new { id = comment.PostId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sharver/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sharver.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace Sharver.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();

        // GET: Posts
        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            var posts = db.Posts.Include(p => p.User);
            return View(await posts.ToListAsync());
        }

        // GET: Posts/Details/5
        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await db.Posts
                .FirstOrDefaultAsync(p => p.Id == id);
                
                // query the database using EF here.
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( PostDTO postDto)
        {
            Post post = new Post();
            if (ModelState.IsValid)
            {
                post.Title = postDto.Title;
                post.Flair = postDto.Flair;
                post.Type = postDto.Type;
                post.UserId = User.Identity.GetUserId();
                post.Created_at = DateTime.Now;
                if(post.Type == 2)
                {
                    string FileExtension = Path.GetExtension(postDto.ImageFile.FileName);
                    var hash = md5.ComputeHash(
                        Encoding.Default.GetBytes(
                            DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString()
                            )
                        );
                    StringBuilder sb = new StringBuilder();
                    for (int i = 0; i < hash.Length; i++)
                    {
                        sb.Append(hash[i].ToString("X2"));
                    }
                    string FileName = sb.ToString() + FileExtension;
                    string UploadPath = Path.Combine(Server.MapPath("~/Uploads"), FileName);
                    postDto.ImageFile.SaveAs(UploadPath);
                    post.Content = FileName;
                }
                else
                {
                    post.Content = postDto.Content;
                }
                db.Posts.Add(post);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = post.Id });
            }

            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", post.UserId);
            return View(postDto);
        }

        // GET: Posts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            if(post.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", post.UserId);
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Exclude = "Created_at")]Post post)
        {
            if (ModelState.IsValid)
            {
                var change = db.Posts.FirstOrDefault(p => p.Id == post.Id);
                if (change.UserId != User.Identity.GetUserId())
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }
                change.Title = post.Title;
                change.Content = post.Content;
                change.Flair = post.Flair;
                change.Updated_at = DateTime.Now;
                db.Entry(change).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", post.UserId);
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            if (post.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Post post = await db.Posts.FindAsync(id);
            if (post.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            db.Posts.Remove(post);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public string UploadFile(HttpPostedFileBase file)
        {
            if (file.ContentLength <= 0)
                throw new Exception("Error while uploading");

            string fileName = Path.GetFileName(file.FileName);
            string path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
            file.SaveAs(path);
            return "Successfuly uploaded";
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sharver/Views/Posts/Create.cshtml
@model Sharver.Models.PostDTO

@{
    ViewBag.Title = "Stwórz nowy post";
}

<h2>Stwórz nowy post</h2>


@using (Html.BeginForm("Create", "Posts", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))

{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, "Tytuł", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" style="margin-left: 12%">
        <div style="margin-bottom:7px;"><strong>Typ wpisu</strong></div>
        <div class="col-md-10">
            <label> @Html.RadioButtonFor(model => model.Type, 0, new { @checked = true }) Tekstowy</label>
        </div>
        <div class="col-md-10">
            <label> @Html.RadioButtonFor(model => model.Type, 1) Link</label>
        </div>
        <div class="col-md-10">
            <label> @Html.RadioButtonFor(model => model.Type, 2) Plik</label>
        </div>

    </div>

    <div class="form-group  textarea-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Content, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group  file-group">
        <div class="col-md-10">
            <input style="margin-left: 12%" type="file" name="ImageFile" />
        </div>

    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Flair, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flair, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Flair, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Stwórz" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Wróc do listy", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sharver/Views/Posts/Delete.cshtml
@model Sharver.Models.Post

@{
    ViewBag.Title = "Usuń";
}

<h3>Czy na pewno chcesz to usunąć?</h3>
<br />
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
<br />

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="text-align: center;width: 33%;">
            <input type="submit" value="Usuń" class="btn btn-default" /> <br />
            @Html.ActionLink("Wróć do listy zarządzania", "Index")
        </div>
    }
</div>

Sharver/Views/Posts/Details.cshtml
@using Microsoft.AspNet.Identity
@model Sharver.Models.Post

@{
    ViewBag.Title = @Model.Title;
}

<div class="postSingle" data-id="@Model.Id">
    <div class="postSingle__rating">
        @{ var score = Model.PostRating.Where(r => r.UserId == User.Identity.GetUserId()).FirstOrDefault();
            bool upDoot = (score is null) ? false : score.Rating;
            bool downDoot = (score is null) ? false : !score.Rating;

        }
        <div class="postSingle__up postSingle__doot @(upDoot ? "active" : "" )"></div>
        <div class="postSingle__score" data-score="@Model.Score">@Model.Score</div>
        <div class="postSingle__down postSingle__doot @(downDoot ? "active" : "" )"></div>
    </div>
    <div class="content">
        <h1>@Model.Title</h1>
        <div>
            @if (Model.Type == 2)
            {
                <img style="width:100%; height:auto;" src="/Uploads/@Model.Content" />
            }
            else if (Model.Type == 1)
            {
                <img style="width:100%; height:auto;" src="@Model.Content" />
            }
            else
            {
                foreach (var line in (Model.Content ?? "").Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None))
                {
                    <p>@line</p>
                }
            }
        </div>
        <p class="tagline">
            <a href="/Users/Posts/@Model.User.Id">@Model.User.UserName</a>
            <time datetime="@Model.Created_at">@Model.Created_at</time>
        </p>
    </div>
</div>
<div>

    @Html.ActionLink("Edycja", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Wróć do listy", "Index", "Home")
</div>

@if (Request.IsAuthenticated)
{
    <div class="reply">
        <div>Dodaj nowy komentarz</div>
        @Html.Partial("_CommentReplyPartial", new ViewDataDictionary { { "post", Model.Id } })
    </div>
}
else
{
    <div class="reply">
        <div>Zaloguj się lub zarejestruj, żeby dodawać komentarze</div>
    </div>
}

<h2>Komentarze(@Model.Comments.Count())</h2>
@if (!Model.Comments.Where(c => c.ParentId is null).Any())
{
    <div>Nie ma jeszcze komentarzy, może chcesz dodać pierwszy?</div>
}

@foreach (var comment in Model.Comments.Where(c => c.ParentId is null))
{
    Html.RenderPartial("_CommentChainPartial", comment);
}

Sharver/Views/Posts/Edit.cshtml
@model Sharver.Models.Post

@{
    ViewBag.Title = "Edycja";
}

<h2>Edycja</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.UserId)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    @if (Model.Type == 0)
    {
    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>
    }

    <div class="form-group">
        @Html.LabelFor(model => model.Flair, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flair, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Flair, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index","Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sharver/Views/Posts/Index.cshtml
@model IEnumerable<Sharver.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Lista</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created_at)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Updated_at)
        </th>
        <th>Opcje</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created_at)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Updated_at)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detale", "Details", new { id=item.Id }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Sharver/Views/Posts/_CommentChainPartial.cshtml
@model Sharver.Models.Comment

<div class="comment__block">
    <div class="parent">
        @Html.Partial("_CommentPartial", Model)
    </div>
    @if(Model.Children.Count > 0)
    { 
        <div>
            <div class="children" style="margin-left:15px">
                @foreach (var child in Model.Children)
                {
                    @Html.Partial("_CommentChainPartial", child)
                }
            </div>
        </div>
    }
</div>

Sharver/Views/Posts/_CommentPartial.cshtml
@using Microsoft.AspNet.Identity
@model Sharver.Models.Comment

<div class="CommentSingle" data-id="@Model.Id">
    <div class="CommentSingle__rating">
        @{ var score = Model.CommentRating.Where(r => r.UserId == User.Identity.GetUserId()).FirstOrDefault();
            bool upDoot = (score is null) ? false : score.Rating;
            bool downDoot = (score is null) ? false : !score.Rating;

        }
        <div class="CommentSingle__up CommentSingle__doot @(upDoot ? "active" : "" )"></div>
        <div class="CommentSingle__score" data-score="@Model.Score">@Model.Score</div>
        <div class="CommentSingle__down CommentSingle__doot @(downDoot ? "active" : "" )"></div>
    </div>
    <div class="content">
        <p class="tagline">
            <a href="/Users/Posts/@Model.User.Id">@Model.User.UserName</a>
            <time datetime="@Model.Created_at">@Model.Created_at</time>
        </p>
        <div class="content">
            @foreach (var line in Model.Content.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None))
            {
                <p>@line</p>
            }
        </div>
    </div>
</div>
@if (Request.IsAuthenticated)
{
<div class="reply" data-id="@Model.Id">
    @Html.Partial("_CommentReplyPartial", new ViewDataDictionary { { "post", Model.PostId }, { "parent", Model.Id } })
</div>
}

Sharver/Views/Posts/_CommentReplyPartial.cshtml
@model Sharver.Models.Comment
@using Microsoft.AspNet.Identity

@using (Html.BeginForm("Create","Comments"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.Hidden("PostId", ViewData["post"])
    @Html.Hidden("ParentId", ViewData["parent"])
    @Html.Hidden("UserId", User.Identity.GetUserId())
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class=" col-md-10">
            <input type="submit" value="Reply" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}